/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './ng2-img-max.module';
import * as import2 from 'ng2-pica/dist/src/ng2-pica.module';
import * as import3 from 'ng2-pica/dist/src/img-exif.service';
import * as import4 from 'ng2-pica/dist/src/ng2-pica.service';
import * as import5 from './img-exif.service';
import * as import6 from './img-maxpx-size.service';
import * as import7 from './img-max-size.service';
import * as import8 from './ng2-img-max.service';
import * as import9 from '@angular/core/src/di/injector';
class Ng2ImgMaxModuleInjector extends import0.NgModuleInjector<import1.Ng2ImgMaxModule> {
  _Ng2PicaModule_0:import2.Ng2PicaModule;
  _Ng2ImgMaxModule_1:import1.Ng2ImgMaxModule;
  __ImgExifService_2:import3.ImgExifService;
  __Ng2PicaService_3:import4.Ng2PicaService;
  __ImgExifService_4:import5.ImgExifService;
  __ImgMaxPXSizeService_5:import6.ImgMaxPXSizeService;
  __ImgMaxSizeService_6:import7.ImgMaxSizeService;
  __Ng2ImgMaxService_7:import8.Ng2ImgMaxService;
  constructor(parent:import9.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _ImgExifService_2():import3.ImgExifService {
    if ((this.__ImgExifService_2 == null)) { (this.__ImgExifService_2 = new import3.ImgExifService()); }
    return this.__ImgExifService_2;
  }
  get _Ng2PicaService_3():import4.Ng2PicaService {
    if ((this.__Ng2PicaService_3 == null)) { (this.__Ng2PicaService_3 = new import4.Ng2PicaService(this._ImgExifService_2)); }
    return this.__Ng2PicaService_3;
  }
  get _ImgExifService_4():import5.ImgExifService {
    if ((this.__ImgExifService_4 == null)) { (this.__ImgExifService_4 = new import5.ImgExifService()); }
    return this.__ImgExifService_4;
  }
  get _ImgMaxPXSizeService_5():import6.ImgMaxPXSizeService {
    if ((this.__ImgMaxPXSizeService_5 == null)) { (this.__ImgMaxPXSizeService_5 = new import6.ImgMaxPXSizeService(this._Ng2PicaService_3,this._ImgExifService_4)); }
    return this.__ImgMaxPXSizeService_5;
  }
  get _ImgMaxSizeService_6():import7.ImgMaxSizeService {
    if ((this.__ImgMaxSizeService_6 == null)) { (this.__ImgMaxSizeService_6 = new import7.ImgMaxSizeService(this._ImgExifService_4)); }
    return this.__ImgMaxSizeService_6;
  }
  get _Ng2ImgMaxService_7():import8.Ng2ImgMaxService {
    if ((this.__Ng2ImgMaxService_7 == null)) { (this.__Ng2ImgMaxService_7 = new import8.Ng2ImgMaxService(this._ImgMaxSizeService_6,this._ImgMaxPXSizeService_5,this._ImgExifService_4)); }
    return this.__Ng2ImgMaxService_7;
  }
  createInternal():import1.Ng2ImgMaxModule {
    this._Ng2PicaModule_0 = new import2.Ng2PicaModule();
    this._Ng2ImgMaxModule_1 = new import1.Ng2ImgMaxModule();
    return this._Ng2ImgMaxModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.Ng2PicaModule)) { return this._Ng2PicaModule_0; }
    if ((token === import1.Ng2ImgMaxModule)) { return this._Ng2ImgMaxModule_1; }
    if ((token === import3.ImgExifService)) { return this._ImgExifService_2; }
    if ((token === import4.Ng2PicaService)) { return this._Ng2PicaService_3; }
    if ((token === import5.ImgExifService)) { return this._ImgExifService_4; }
    if ((token === import6.ImgMaxPXSizeService)) { return this._ImgMaxPXSizeService_5; }
    if ((token === import7.ImgMaxSizeService)) { return this._ImgMaxSizeService_6; }
    if ((token === import8.Ng2ImgMaxService)) { return this._Ng2ImgMaxService_7; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2ImgMaxModuleNgFactory:import0.NgModuleFactory<import1.Ng2ImgMaxModule> = new import0.NgModuleFactory(Ng2ImgMaxModuleInjector,import1.Ng2ImgMaxModule);